# Basic info
replicaCount: 1
secretsRef: "__REQUIRED__"
image:
  repository: registry.hub.docker.com/datamountaineer/kafka-connect-druid
  tag: 1.0.0
  pullPolicy: IfNotPresent

# Resource management
resources:
  limits:
    memory: 512Mi
  requests:
    memory: 256Mi
javaHeap: 256M

# Monitoring
monitoring:
  pipeline: "__REQUIRED__"
  enabled: true
  port: 9102
  path: "/metrics"

# SSL/TLS options can be enabled, some connectors provide SSL support, others the newer TLS
# Set the corresponding value type to true. For SSL persistent volumes or hostPaths will be
# mounted under /connector-extra-config. Set the connectors ssl/tls option paths to be use this
# TLS is done via Secrets, create a secret for containing the certificates (base64 encoded) and
# create a secret for them, adding the name of the secret to the `secretsRef` other wise if using
# Eneco's Landscaper it will do this for you.

# SSL mount path on hosts, should be the base path of any ssl keystore/truststore paths
ssl:
  enabled: true
  # Path to the directory on the hosts
  path: /ssl

  # If persistent volumes should be used for ssl keystore/truststore paths
  persistentVolumes:
    enabled: false
    existingClaim:

# TLS, for those connectors supporting TLS certificates rather than ssl key/truststores
# contents for mount take from config map
tls:
  enabled: true

# lenses 
lensesUser: ""

# Connect values
clusterName: "__REQUIRED__"
bootstrapServers: kafka:9092
schemaRegistryURL: "http://schema-registry:8081"
restPort: 8083
logLevel: INFO
keyConverter: "io.confluent.connect.avro.AvroConverter"
valueConveter: "io.confluent.connect.avro.AvroConverter"

javaHeap: "256M"

## Avro schemas, for those connectors, MQTT and JMS source that support Avro converters we
## need the schemas, so we'll mount as a ConfigMap. Set the key value pairs, filename and data
## matching the value option avroSchema. Key is the file name, value is the avro schema contents
#avroSchemaFiles:
#  schema_file_name:  ""

# applicationId name of the connector
applicationId: "__REQUIRED__"

connectorClass: "com.datamountaineer.streamreactor.connect.druid.DruidSinkConnector"

#maxTasks The number of tasks to spawn
maxTasks: 1

# kcql The KCQL statement to specify field selection from topics and druid datasource targets. type: STRING importance: HIGH
kcql: "__REQUIRED__"

# configFile The path to the configuration file. type: STRING importance: HIGH
configFile: "__REQUIRED__"

# writeTimeout 
# Specifies the number of seconds to wait for the write to Druid to happen.
#      type: INT importance: LOW
writeTimeout: 6000

# enabled Enables the output for how many records have been processed type: BOOLEAN importance: MEDIUM
progressEnabled: true

