apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        hostPort: {{ .Values.restPort | quote }}
        containerPort: {{ .Values.restPort | quote }}
        pipeline: {{ .Values.monitoring.pipeline | quote }}
      annotations:
        prometheus.io/scrape: {{ .Values.monitoring.enabled | quote }}
        prometheus.io/port: {{ .Values.monitoring.port | quote }}
        prometheus.io/path: {{ .Values.monitoring.path | quote }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.restPort }}
        livenessProbe:
          exec:
            command:
            - /etc/confluent/liveliness.sh
          initialDelaySeconds: 60
          timeoutSeconds: 5
        resources:
{{ toYaml .Values.resources | indent 10 }}
        env:
        # JVM Heap Allowance
        - name: KAFKA_HEAP_OPTS
          value: -Xmx{{ .Values.javaHeap }}
        - name: KAFKA_JMX_PORT
          value: {{ .Values.jmxPort | quote }}

        - name:  CONNECT_GROUP_ID
          value: {{ .Values.clusterName | quote }}
        - name:  CONNECT_BOOTSTRAP_SERVERS
          value: {{ .Values.bootstrapServers | quote }}
        - name:  CONNECT_REST_PORT
          value: {{ .Values.restPort | quote }}
        - name:  CONNECT_CONFIG_STORAGE_TOPIC
          value: "connect_{{ .Values.clusterName }}_configs"
        - name:  CONNECT_OFFSET_STORAGE_TOPIC
          value: "connect_{{ .Values.clusterName }}_offsets"
        - name:  CONNECT_STATUS_STORAGE_TOPIC
          value: "connect_{{ .Values.clusterName }}_statuses"
        - name:  CONNECT_KEY_CONVERTER
          value: "io.confluent.connect.avro.AvroConverter"
        - name:  CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL
          value: {{ .Values.schemaRegistryURL | quote }}
        - name:  CONNECT_VALUE_CONVERTER
          value: "io.confluent.connect.avro.AvroConverter"
        - name:  CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL
          value: {{ .Values.schemaRegistryURL | quote }}
        - name:  CONNECT_INTERNAL_KEY_CONVERTER
          value: "org.apache.kafka.connect.json.JsonConverter"
        - name:  CONNECT_INTERNAL_VALUE_CONVERTER
          value: "org.apache.kafka.connect.json.JsonConverter"
        - name:  CONNECT_CONSUMER_SESSION_TIMEOUT_MS
          value: {{ .Values.sessionTimeoutMs | quote }}
        - name:  CONNECT_CONSUMER_REQUEST_TIMEOUT_MS
          value: {{ .Values.requestTimeoutMs | quote }}
        - name:  CONNECT_OFFSET_FLUSH_INTERVAL_MS
          value: {{ .Values.partitioner.offsetFlushIntervalMs | quote }}
        - name: CONNECT_REST_ADVERTISED_HOST_NAME
          valueFrom:
            fieldRef:
              fieldPath: status.podIP

        # Connector properties
        - name: CONNECTOR_NAME
          value: {{ .Values.applicationId | quote }}
        - name: CONNECTOR_GROUP_ID
          value: {{ .Values.applicationId | quote }}
        - name: CONNECTOR_CONNECTOR_CLASS
          value: {{ .Values.connectorClass | quote }}
        - name: CONNECTOR_TIMEZONE
          value: {{ .Values.timezone | quote }}
        - name: CONNECTOR_LOCALE
          value: {{ .Values.locale | quote }}
        - name: CONNECTOR_TASKS_MAX
          value: {{ .Values.tasksMax | quote }}
        - name: CONNECTOR_TOPICS
          value: {{ .Values.topics | quote }}
        - name: CONNECTOR_RETRY_BACKOFF_MS
          value: {{ .Values.retryBackoffMs | quote }}
        - name: CONNECTOR_SHUTDOWN_TIMEOUT_MS
          value: {{ .Values.shutdownTimeoutMs | quote }}
        - name: CONNECTOR_FILENAME_OFFSET_ZERO_PAD_WIDTH
          value: {{ .Values.hdfs.filenameOffsetZeroPadWidth | quote }}
        - name: CONNECTOR_TOPICS_DIR
          value: {{ .Values.hdfs.topicsDir | quote }}
        - name: CONNECTOR_LOGS_DIR
          value: {{ .Values.hdfs.logsDir | quote }}
        - name: CONNECTOR_FORMAT_CLASS
          value: {{ .Values.hdfs.formatClass | quote }}
        - name: CONNECTOR_HDFS_URL
          value: {{ .Values.hdfs.url | quote }}
        - name: CONNECTOR_HADOOP_CONF_DIR
          value: {{ .Values.hdfs.confDir | quote }}

        # Partition strategy
        - name: CONNECTOR_PARTITIONER_CLASS
          value: {{ .Values.partitioner.class | quote }}
        - name: CONNECTOR_FLUSH_SIZE
          value: {{ .Values.partitioner.flushSize | quote }}
        - name: CONNECTOR_ROTATE_INTERVAL_MS
          value: {{ .Values.partitioner.rotateIntervalMs | quote }}
          {{- if .Values.partitioner.rotateScheduleIntervalMs }}
        - name: CONNECTOR_ROTATE_SCHEDULE_INTERVAL_MS
          value: {{ .Values.partitioner.rotateScheduleIntervalMs | quote }}
          {{- end }}
          {{- if .Values.partitioner.fieldName }}
        - name: CONNECTOR_PARTITION_FIELD_NAME
          value: {{ .Values.partitioner.fieldName | quote }}
          {{- end }}

        # Hive Integration
        - name: CONNECTOR_HIVE_INTEGRATION
          value: {{ .Values.hive.integration | quote }}
        - name: CONNECTOR_HIVE_METASTORE_URIS
          value: {{ .Values.hive.metastoreURIs | quote }}
        - name: CONNECTOR_HIVE_CONF_DIR
          value: {{ .Values.hive.confDir | quote }}
        - name: CONNECTOR_SCHEMA_COMPATIBILITY
          value: {{ .Values.hive.schemaCompatibility | quote }}
        - name: CONNECTOR_HIVE_DATABASE
          value: {{ .Values.hive.database | quote }}

        # Cloudera properties
        {{- if .Values.cloudera.managerURL }}
        - name:  CLOUDERA_CLUSTER_NAME
          value: {{ .Values.cloudera.clusterName | quote }}
        - name:  CLOUDERA_MANAGER_URL
          value: {{ .Values.cloudera.managerURL | quote }}
        {{- end }}

