# Basic info
replicaCount: "__REQUIRED__"
secretsRef: "__REQUIRED__"
image:
  repository: registry.hub.docker.com/datamountaineer/kafka-connect-azure-documentdb
  tag: 0.2.6
  pullPolicy: IfNotPresent

# Resource management
resources:
  limits:
    memory: 512Mi
  requests:
    memory: 256Mi
javaHeap: 256M

# Service info
service:
  internalPort: 8083

# Connect values
clusterName: 
bootstrapServers: kafka:9092
schemaRegistryURL: http://schema-registry:8081
restPort: 8083
logLevel: INFO

# Connector values
applicationId: 
connectorClass: com.datamountaineer.streamreactor.connect.azure.documentdb.sink.DocumentDbSinkConnector
tasksMax: "__REQUIRED__"
topics: "__REQUIRED__"

# Connection
connectDocumentDBDatabaseName: "__REQUIRED__"
connectDocumentDBEndpoint: "__REQUIRED__"
connectDocumentDBMasterKey: "__REQUIRED__"
connectDocumentDBSinkBatchSize: 100
connectDocumentDBSinkConsistencyLevel: "Session"
connectDocumentDBSinkCreateDatabase: false
connectDocumentDBProxy: false

#routing
connectDocumentDBSinkKCQL: "__REQUIRED__"


#Error policies
connectDocumentDBErrorPolicy: "THROW"
connectDocumentDBRetryInterval: "60000"
connectDocumentDBMaxRetries: 20

connectProgressEnabled: true

# Monitoring
monitoring:
  pipeline: "__REQUIRED__"
  enabled: true
  port: 9102
  path: "/metrics"