apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    app: {{ template "fullname" . }}
  annotations:
    "helm.sh/hook": pre-install
data:
  connect.mqtt.password: {{ .Values.password }}
  {{- if .Values.tlsEnabled }}
  server.crt: {{ .Values.serverCrt }}
  ca.crt: {{ .Values.caCert }}
  server.key: {{ .Values.serverKey }}
  {{- end -}}