---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.name }}
provisioner: {{ .Values.provisioner }}  
parameters:
  skuName: {{ .Values.skuName }}
  location: {{ .Valueslocation }}
  storageAccount: {{ .Values.storageAccount }}

