apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    app: {{ template "fullname" . }}
  annotations:
    "helm.sh/hook": pre-install
data:
  connect.mongo.password: {{ .Values.password }}
  {{- if .Values.sslEnabled }}
  connect.mongo.key.store.password: {{ .Values.keyStorePassword }}
  connect.mongo.trust.store.password: {{ .Values.trustStorePassword }}
  client.truststore.jks: {{ .Values.trustStoreFileData }}
  client.keystore.jks: {{ .Values.keyStoreFileData }}
  {{- end -}}