apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        hostPort: {{ .Values.restPort | quote }}
        containerPort: {{ .Values.restPort | quote }}
        pipeline: {{ .Values.monitoring.pipeline | quote }}
      annotations:
        prometheus.io/scrape: {{ .Values.monitoring.enabled | quote }}
        prometheus.io/port: {{ .Values.monitoring.port | quote }}
        prometheus.io/path: {{ .Values.monitoring.path | quote }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.restPort }}
          name: connect-rest
        - containerPort: {{ .Values.monitoring.port }}
          name: connect-jmx
        livenessProbe:
          exec:
            command:
            - /etc/confluent/liveliness.sh
          initialDelaySeconds: 30
          timeoutSeconds: 5
        resources:
{{ toYaml .Values.resources | indent 10 }}
        env:
        # JVM Heap Allowance
        - name: KAFKA_HEAP_OPTS
          value: -Xmx{{ .Values.javaHeap }}
        - name: CONNECT_LOG4J_ROOT_LOGLEVEL
          value: {{ .Values.logLevel | quote }}
        - name:  CONNECT_GROUP_ID
          value: {{ .Values.clusterName | quote }}
        - name:  CONNECT_BOOTSTRAP_SERVERS
          value: {{ .Values.bootstrapServers | quote }}
        - name:  CONNECT_REST_PORT
          value: {{ .Values.restPort | quote }}
        - name:  CONNECT_CONFIG_STORAGE_TOPIC
          value: "connect_{{ .Values.clusterName }}_configs"
        - name:  CONNECT_OFFSET_STORAGE_TOPIC
          value: "connect_{{ .Values.clusterName }}_offsets"
        - name:  CONNECT_STATUS_STORAGE_TOPIC
          value: "connect_{{ .Values.clusterName }}_statuses"
        - name:  CONNECT_KEY_CONVERTER
          value: "io.confluent.connect.avro.AvroConverter"
        - name:  CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL
          value: {{ .Values.schemaRegistryURL | quote }}
        - name:  CONNECT_VALUE_CONVERTER
          value: "io.confluent.connect.avro.AvroConverter"
        - name:  CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL
          value: {{ .Values.schemaRegistryURL | quote }}
        - name:  CONNECT_INTERNAL_KEY_CONVERTER
          value: "org.apache.kafka.connect.json.JsonConverter"
        - name:  CONNECT_INTERNAL_VALUE_CONVERTER
          value: "org.apache.kafka.connect.json.JsonConverter"
        - name: CONNECT_REST_ADVERTISED_HOST_NAME
          valueFrom:
            fieldRef:
              fieldPath: status.podIP

        # Connector properties
        - name: CONNECTOR_NAME
          value: {{ .Values.applicationId | quote }}
        - name: CONNECTOR_GROUP_ID
          value: {{ .Values.applicationId | quote }}
        - name: CONNECTOR_CONNECTOR_CLASS
          value: {{ .Values.connectorClass | quote }}
        - name: CONNECTOR_TASKS_MAX
          value: {{ .Values.tasksMax | quote }}

        - name: CONNECTOR_MODE
          value: {{ .Values.mode | quote }}
        - name: CONNECTOR_CONNECTION_USER
          value: {{ .Values.user | quote }}
        - name: CONNECTOR_CONNECTION_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secretsRef | quote }}
              key: {{ .Values.passwordKey | quote }}
        - name: CONNECTOR_CONNECTION_URL
          value: {{ .Values.connectionUrl | quote }}
        - name: CONNECTOR_TOPIC_PREFIX
          value: {{ .Values.topicPrefix | quote }}
        - name: CONNECTOR_MAX_BATCH_ROWS
          value: {{ .Values.batchMaxRows | quote }}
        {{ if .Values.pollInterval }}
        - name: CONNECTOR_POLL_INTERVAL
          value: {{ .Values.pollInterval | quote }}
        {{end}}
        {{ if .Values.pollInterval }}
        - name: CONNECTOR_POLL_INTERVAL
          value: {{ .Values.pollInterval | quote }}
        {{end}}
        {{ if .Values.numericPrecisionMapping }}
        - name: CONNECTOR_NUMERIC_PRECISION_MAPPING
          value: {{ .Values.numericPrecisionMapping | quote }}
        {{end}}
        {{ if .Values.tablePollIntervalMs }}
        - name: CONNECTOR_TABLE_POLL_INTERVAL_MS
          value: {{ .Values.tablePollIntervalMs | quote }}
        {{end}}
        {{ if .Values.timestampColumnName }}
        - name: CONNECTOR_TIMESTAMP_COLUMN_NAME
          value: {{ .Values.timestampColumnName | quote }}
        {{end}}
        {{ if .Values.incrementColumnName }}
        - name: CONNECTOR_INCREMENTING_COLUMN_NAME
          value: {{ .Values.incrementColumnName | quote }}
        {{end}}
        {{ if .Values.tableBlackList }}
        - name: CONNECTOR_TABLE_BLACK_LIST
          value: {{ .Values.tableBlackList | quote }}
        {{end}}
        {{ if .Values.tableWhiteList }}
        - name: CONNECTOR_TABLE_WHITE_LIST
          value: {{ .Values.tableWhiteList | quote }}
        {{end}}
        {{ if .Values.schemaPattern }}
        - name: CONNECTOR_SCHEMA_PATTERN
          value: {{ .Values.schemaPattern | quote }}
        {{end}}
        {{ if .Values.query }}
        - name: CONNECTOR_QUERY
          value: {{ .Values.query | quote }}
        {{end}}
        {{ if .Values.validateNonNull }}
        - name: CONNECTOR_VALIDATE_NON_NULL
          value: {{ .Values.validateNonNull | quote }}
        {{end}}
        {{ if .Values.timestampDelayIntervalMs }}
        - name: CONNECTOR_TIMESTAMP_DELAY_INTERVAL_MS
          value: {{ .Values.timestampDelayIntervalMs | quote }}
        {{end}}
        {{ if .Values.tableTypes }}
        - name: CONNECTOR_TABLE_TYPES
          value: {{ .Values.tableTypes | quote }}
        {{end}}
        {{ if .Values.limitEnabled }}
        - name: CONNECTOR_LIMIT_ENABLED
          value: {{ .Values.limitEnabled | quote }}
        {{end}}
        {{ if .Values.limit }}
        - name: CONNECTOR_LIMIT
          value: {{ .Values.limit | quote }}
        {{end}}