{{- if .Values.ssl.enabled}}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Values.server.name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: "{{ template "fullname" . }}-tls"
data:
  private-key.pem: {{ toYaml .Values.privateKeyFileData | indent 2 }}
  public-key.pem: {{ toYaml .Values.publicKeyFileData | indent 2 }}
{{- end -}}  