apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    app: {{ template "fullname" . }}
  annotations:
    "helm.sh/hook": pre-install
data:
  connect.coap.password: {{ .Values.password }}
  {{- if .Values.sslEnabled }}
  connect.coap.truststore.pass: {{ .Values.trustStorePass }}
  connect.coap.keystore.pass: {{ .Values.keyStorePass }}
  client.truststore.jks: {{ .Values.trustStoreFileData }}
  client.keystore.jks: {{ .Values.keyStoreFileData }}
  private-key.pem: {{ toYaml .Values.privateKeyFileData | indent 2 }}
  public-key.pem: {{ toYaml .Values.publicKeyFileData | indent 2 }}
  {{- end -}}