apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    app: {{ template "fullname" . }}
  annotations:
    "helm.sh/hook": pre-install
data:
  password: {{ .Values.password }}
  truststorePass: {{ .Values.truststorePass }}
  keystorePass: {{ .Values.keystorePass }}
