# Basic info
replicaCount: 3
secretsRef: 
image:
  repository: registry.hub.docker.com/datamountaineer/kafka-connect-cassandra
  tag: 0.2.5
  pullPolicy: Always

# Resource management
resources:
  limits:
    memory: 512Mi
  requests:
    memory: 256Mi
javaHeap: 256M

# Service info
service:
  internalPort: 8083

# Connect values
clusterName: 
bootstrapServers: kafka:9092
schemaRegistryURL: http://schema-registry:8081
restPort: 8083
logLevel: INFO

# Connector values
applicationId:
connectorClass: com.datamountaineer.streamreactor.connect.cassandra.source.CassandraSourceConnector
tasksMax: 3
topics: 
connectCassandraSourceKcql: 

# Connection
connectCassandraContactPoints: 
connectCassandraPort: 
connectCassandraKeySpace: 
connectCassandraUsername: 

#SSL
connectCassandraSslEnabled: false
connectCassandraTrustStorePath: 
connectCassandraTrustStorePasswordKey: "TrustStorePasswordKey"
connectCassandraTrustStorePassword: 
connectCassandraTrustStoreType: "JKS"
connectCassandraSslClientCertAuth: false
connectCassandraKeyStorePath: 
connectCassandraKeyStorePasswordKey: "KeyStorePasswordKey"
connectCassandraKeyStorePassword: 
connectCassandraKeyStoreType: "JKS"

#Error policies
connectCassandraErrorPolicy: "THROW"
connectCassandraRetryInterval: "60000"
connectCassandraMaxRetries: 20

# Source specific
connectCassandraImportMode:
connectCassandraSourceTaskBatchSize: 100
connectCassandraSourceFetchSize: 5000
connectCassandraSourceTaskBufferSize: 10000
connectCassandraImportSourceAllowFiltering: true
connectCassandraConsistencyLevel: ""
connectCassandraSourceTimestampType: "timeuuid"

connectProgressEnabled: true

# Monitoring
monitoring:
  pipeline: 
  enabled: true
  port: 9102
  path: "/metrics"