apiVersion: v1
kind: Secret
metadata:
  name: "{{ template "fullname" . }}-tls"
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    app: "{{ template "fullname" . }}-tls"
  annotations:
    "helm.sh/hook": pre-install
data:
  client-cert.pem: {{ .Values.tlsCert }}
  ca-cert.pem: {{ .Values.tlsCaCert }}
  client-key.pem: {{ .Values.tlsKey }}