# Basic info
replicaCount: 1

image:
  repository: registry.hub.docker.com/datamountaineer/kafka-connect-ftp
  tag: 0.4.1
  pullPolicy: IfNotPresent

# Resource management
resources:
  limits:
    memory: 512Mi
  requests:
    memory: 256Mi

# Monitoring
monitoring:
  pipeline: "__REQUIRED__"
  enabled: true
  port: 9102
  path: "/metrics"

# lenses 
lensesUser: ""

# Connect values

#javaHeap option
javaHeap: "256M"

# clusterName The connect cluster name. This is the consumer group id for the backing topics
clusterName: "__REQUIRED__"

# bootstrapServers A comma separated list of the kafka brokers
bootstrapServers: kafka:9092

# schemaRegistryURL A comman separated list of the Schema registry URL
schemaRegistryURL: "http://schema-registry:8081"

# restPort The rest port of Connect
restPort: 8083

# logLevel The log4j level
logLevel: INFO

# keyConverter The key converter to/from Connects struct
keyConverter: "io.confluent.connect.avro.AvroConverter"

# valueConverter The key converter to/from Connects struct
valueConveter: "io.confluent.connect.avro.AvroConverter"

# connectorClass
connectorClass: "com.datamountaineer.streamreactor.connect.ftp.source.FtpSourceConnector"

# applicationId name of the connector
applicationId: "__REQUIRED__"

#maxTasks The number of tasks to spawn
maxTasks: 1

# keystyle what the output key is set to: `string` => filename; `struct` => structure with filename and offset type: STRING importance: HIGH
keystyle: "__REQUIRED__"

# maxPollRecords Max number of records returned per poll type: INT importance: LOW
maxPollRecords: 10000

# sourcerecordconverter TODO type: CLASS importance: HIGH
sourcerecordconverter: com.datamountaineer.streamreactor.connect.ftp.source.NopSourceRecordConverter

# monitorTail comma separated lists of path:destinationtopic; tail of file is tracked type: LIST importance: HIGH
monitorTail: 

# maxBackoff on failure, exponentially backoff to at most this ISO8601 duration type: STRING importance: HIGH
maxBackoff: PT30M

# fileconverter TODO type: CLASS importance: HIGH
fileconverter: com.datamountaineer.streamreactor.connect.ftp.source.SimpleFileConverter

# refresh how often the ftp server is polled; ISO8601 duration type: STRING importance: HIGH
refresh: "__REQUIRED__"

# fileMaxage ignore files older than this; ISO8601 duration type: STRING importance: HIGH
fileMaxage: "__REQUIRED__"

# monitorUpdate comma separated lists of path:destinationtopic; whole file is tracked type: LIST importance: HIGH
monitorUpdate: 

# address ftp address[:port] type: STRING importance: HIGH
address: "__REQUIRED__"

# user ftp user name to login type: STRING importance: HIGH
user: "__REQUIRED__"

# protocol FTPS or FTP protocol type: STRING importance: LOW
protocol: ftp

# password ftp password key to login type in the secret
password: "__REQUIRED__"