---
apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: {{ .Values.name | quote }}
spec:
  storageClassName: {{ .Values.storageClassName | quote }}
  capacity:
    storage: {{ .Values.capacity | quote }}
  accessModes: 
    - {{ .Values.accessMode | quote }}
  azureFile:
    secretName:
      valueFrom:
        secretKeyRef:
          name: {{ .Values.secretsRef | quote }}
          key: {{ .Values.storageAccountKey }}
    shareName: {{ .Values.azureFile.shareName | quote }}     
    readOnly: {{ .Values.azureFile.readOnly  }}