apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    app: {{ template "fullname" . }}
  annotations:
    "helm.sh/hook": pre-install
data:
  connect.rethink.password: {{ .Values.password }}
  connect.rethink.rethink.auth.key: {{ .Values.rethinkAuth }}
  {{- if .Values.tlsEnabled }}
  ca.crt: {{ .Values.rethinkCertFileData }}
  {{- end -}}