# Basic info
replicaCount: "__REQUIRED__"
secretsRef: "__REQUIRED__"
image:
  repository: registry.hub.docker.com/datamountaineer/kafka-connect-kudu
  tag: 0.2.6
  pullPolicy: IfNotPresent

# Resource management
resources:
  limits:
    memory: 512Mi
  requests:
    memory: 256Mi
javaHeap: 256M

# Service info
service:
  internalPort: 8083

# Connect values
clusterName: "__REQUIRED__"
bootstrapServers: kafka:9092
schemaRegistryURL: http://schema-registry:8081
restPort: 8083
logLevel: INFO

# Connector values
applicationId: "__REQUIRED__"
connectorClass: com.datamountaineer.streamreactor.connect.kudu.sink.KuduSinkConnector
tasksMax: "__REQUIRED__"
topics: "__REQUIRED__"

# Connection
connectKuduMaster: "localhost"
connectKuduSinkKcql: "__REQUIRED__"

#Error policies
connectKuduSinkErrorPolicy: "THROW"
connectKuduSinkRetryInterval: "60000"
connectKuduSinkMaxRetries: 20

connectProgressEnabled: true

# Monitoring
monitoring:
  pipeline: "__REQUIRED__"
  enabled: true
  port: 9102
  path: "/metrics"