# Basic info
replicaCount:
secretsRef:
image:
  repository: registry.hub.docker.com/datamountaineer/kafka-connect-redis
  tag: 0.2.6
  pullPolicy: IfNotPresent

# Resource management
resources:
  limits:
    memory: 512Mi
  requests:
    memory: 256Mi
javaHeap: 256M

# Service info
service:
  internalPort: 8083

# Connect values
clusterName: 
bootstrapServers: kafka:9092
schemaRegistryURL: http://schema-registry:8081
restPort: 8083
logLevel: INFO

# Connector values
applicationId: 
connectorClass: com.datamountaineer.streamreactor.connect.redis.sink.RedisSinkConnector
tasksMax:
topics: 

# Connection
connectRedisConnectionHost: 
connectRedisConnectionPort:
connectRedisConnectionPasswordKey: redis-password-key
connectRedisSinkKcql:

#Error policies
connectRedisErrorPolicy: "THROW"
connectRedisRetryInterval: "60000"
connectRedisMaxRetries: 20

connectProgressEnabled: true

# Monitoring
monitoring:
  pipeline:
  enabled: true
  port: 9102
  path: "/metrics"