# Basic info
replicaCount: "__REQUIRED__"
secretsRef: "__REQUIRED__"
image:
  repository: registry.hub.docker.com/datamountaineer/kafka-connect-redis
  tag: 0.2.6
  pullPolicy: IfNotPresent

# Resource management
resources:
  limits:
    memory: 512Mi
  requests:
    memory: 256Mi
javaHeap: 256M

# Service info
service:
  internalPort: 8083

# Connect values
clusterName: "__REQUIRED__"
bootstrapServers: kafka:9092
schemaRegistryURL: http://schema-registry:8081
restPort: 8083
logLevel: INFO

# Connector values
applicationId: "__REQUIRED__"
connectorClass: com.datamountaineer.streamreactor.connect.redis.sink.RedisSinkConnector
tasksMax: "__REQUIRED__"
topics: "__REQUIRED__"

# Connection
connectRedisConnectionHost: "__REQUIRED__"
connectRedisConnectionPort: "__REQUIRED__"
connectRedisConnectionPasswordKey: "__REQUIRED__"
connectRedisSinkKcql: "__REQUIRED__"

#Error policies
connectRedisErrorPolicy: "THROW"
connectRedisRetryInterval: "60000"
connectRedisMaxRetries: 20

connectProgressEnabled: true

# Monitoring
monitoring:
  pipeline: "__REQUIRED__"
  enabled: true
  port: 9102
  path: "/metrics"